# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: oldrel
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
notifications:
  email:
    - fmhoeger@mirsem.org

before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_github("rstudio/rmarkdown"); install.packages("shinytest"); shinytest::installDependencies()'

after_success:
  - travis_wait Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libgit2-dev
